import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TodosProvider } from './context/TodosContext'
import LinkButton from './utils/LinkButton'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="tr">
      <head>
        <title>Nextjs Server Operations</title>
      </head>
      
      <body className={`${inter.className} py-4 px-8`}>
        <nav className='flex gap-4'>
          <LinkButton url="/">Home</LinkButton>
          <LinkButton url="/todos">Todos</LinkButton>
          <LinkButton url="/create">Create Todo</LinkButton>
        </nav>
        <TodosProvider>
          {children}
        </TodosProvider>
      </body>
    </html>
  )
}
